---
abstract: 'Perl extension for tagging terms in a text'
author:
  - 'Thierry Hamon <thierry.hamon@univ-paris13.fr>'
build_requires:
  Module::Build: 0.28
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Alvis-TermTagger
provides:
  Alvis::TermTagger:
    file: lib/Alvis/TermTagger.pm
    version: 0.7
requires:
  Getopt::Long: 0
  Pod::Usage: 0
  Test::More: 0.62
  perl: 5.005
resources:
  license: http://opensource.org/licenses/gpl-license.php
version: 0.7
