#!/usr/bin/perl -w


use strict;

require Alvis::TermTagger;

my $corpus = "corpus";
my $termlist = "termlist";
my $selected_term_list = "selected-terms";

Alvis::TermTagger::termtagging($corpus, $termlist, $selected_term_list);


warn "List of the selected terms in $selected_term_list\n";

